global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: eventrelay-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: eventrelay-api

  - job_name: eventrelay-dispatcher
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          service: eventrelay-dispatcher
